- name: stop the service
  ansible.builtin.service:
    name: "{{ item }}"
    state: absent

- name: remove /app directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: create /app directory
  ansible.builtin.file:
     name: /app
     state: directory 

- name: Download apllication
  ansible.builtin.unarchive: 
    src: https://roboshop-artifacts.s3.amazonaws.com/{{ comonent }}-v{{ app_version }}.zip 
    dest: /app

- name: install depemndencies
  community.general.npm:
    path: /app

- name: restart {{ component }}
  ansible.builtin.dnf: 
    name: "{{ component }}"
    state: restarted          